// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: proto/search_movie.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SearchMovieClient is the client API for SearchMovie service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchMovieClient interface {
	GetMovie(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type searchMovieClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchMovieClient(cc grpc.ClientConnInterface) SearchMovieClient {
	return &searchMovieClient{cc}
}

func (c *searchMovieClient) GetMovie(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/search_movie.SearchMovie/GetMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchMovieServer is the server API for SearchMovie service.
// All implementations must embed UnimplementedSearchMovieServer
// for forward compatibility
type SearchMovieServer interface {
	GetMovie(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedSearchMovieServer()
}

// UnimplementedSearchMovieServer must be embedded to have forward compatible implementations.
type UnimplementedSearchMovieServer struct {
}

func (UnimplementedSearchMovieServer) GetMovie(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMovie not implemented")
}
func (UnimplementedSearchMovieServer) mustEmbedUnimplementedSearchMovieServer() {}

// UnsafeSearchMovieServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchMovieServer will
// result in compilation errors.
type UnsafeSearchMovieServer interface {
	mustEmbedUnimplementedSearchMovieServer()
}

func RegisterSearchMovieServer(s grpc.ServiceRegistrar, srv SearchMovieServer) {
	s.RegisterService(&SearchMovie_ServiceDesc, srv)
}

func _SearchMovie_GetMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchMovieServer).GetMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search_movie.SearchMovie/GetMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchMovieServer).GetMovie(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchMovie_ServiceDesc is the grpc.ServiceDesc for SearchMovie service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchMovie_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search_movie.SearchMovie",
	HandlerType: (*SearchMovieServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMovie",
			Handler:    _SearchMovie_GetMovie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/search_movie.proto",
}
